# Generated by Django 2.0.8 on 2018-12-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_fetcher', '0002_auto_20181210_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fetcher',
            name='file_path',
        ),
    ]
