# Generated by Django 2.0.8 on 2018-12-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_fetcher', '0003_remove_fetcher_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetcher',
            name='file_path',
            field=models.CharField(default='None', help_text="You don't have to fill it", max_length=100),
        ),
    ]
