# Generated by Django 2.0.8 on 2018-12-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_fetcher', '0004_fetcher_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fetcher',
            name='file_path',
        ),
    ]
