# Generated by Django 2.0.8 on 2018-12-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_fetcher', '0008_auto_20181214_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetcher',
            name='file_path',
            field=models.CharField(blank=True, help_text="You don't have to fill it", max_length=100, verbose_name='log path'),
        ),
    ]
