# Generated by Django 2.0.8 on 2018-12-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_fetcher', '0009_auto_20181214_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetcher',
            name='task_status',
            field=models.CharField(blank=True, choices=[('R', 'running'), ('D', 'done'), ('F', 'failed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fetcher',
            name='app_name',
            field=models.CharField(blank=True, choices=[('A1', 'api_1'), ('E1', 'erp_1')], max_length=10),
        ),
    ]
