# Generated by Django 2.0.8 on 2018-12-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_fetcher', '0010_auto_20181218_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fetcher',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='fetcher',
            name='app_name',
            field=models.CharField(blank=True, choices=[('api_1', 'api_1'), ('erp_1', 'erp_1')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fetcher',
            name='file_path',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='log path'),
        ),
        migrations.AlterField(
            model_name='fetcher',
            name='task_status',
            field=models.CharField(blank=True, choices=[('R', 'running'), ('D', 'done'), ('F', 'failed')], editable=False, max_length=10),
        ),
    ]
